name: Deploy to Fly.io

on:
  push:
    branches:
      - main  # tai mikä deploy-haara sinulla on

jobs:
  deploy:
    name: Deploy to Fly.io
    runs-on: ubuntu-latest

    # ✅ Tämä on uusi osa tehtävään 11.10:
    environment:
      name: production

    steps:
      - uses: actions/checkout@v3

      - name: Install Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to Fly.io
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
