name: Deployment pipeline

on:
  push:
    branches:
      - main

jobs:
  simple-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Hello World
        run: echo "Hello from CI pipeline"
